package com.engine.ingest.model;

import com.engine.ingest.enums.CarDrivingStatus;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Entity
@Table(name = "gps_transactions")
@Getter
@Setter
public class GpsTransactionModel {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;  // Autogenerated ID

    private String customerId;

    private String carId;

    private String officeId;

    private String agentId;

    private LocalDateTime trxnTimestamp;

    private CarDrivingStatus carDrivingStatus;

    private Double currentLongitude;

    private Double currentLatitude;

    private String currentArea;

    private Double km;

    private String sourceSystem;
}
